import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'bn' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'home': 'Home',
    'wallet': 'Wallet',
    'myBets': 'History',
    'profile': 'Profile',
    'live': 'Live',
    'join': 'Join',
    'joinNow': 'JOIN MATCH NOW',
    'totalPlayers': 'Total Players',
    'prizePool': 'Prize Pool',
    'entryFee': 'Entry Fee',
    'matchDetails': 'Match Details',
    'login': 'Login',
    'register': 'Register',
    'balance': 'Balance',
    'deposit': 'Deposit',
    'withdraw': 'Withdraw',
    'gamingArena': 'Gaming Arena',
    'arenaSub': 'Join matches & earn rewards',
    'active': 'Active',
    'completed': 'Completed',
    'history': 'History',
    'details': 'Details',
    'confirmEntry': 'Confirm Your Entry',
    'success': 'Success',
    'joined': 'Joined!',
    'language': 'Language',
    'selectLanguage': 'Select Language',
    'players': 'Players',
    'entry': 'Entry',
    'slotsOccupied': 'Slots Occupied',
    'capacity': 'CAPACITY',
    'fullHouse': 'FULL HOUSE',
    'joinBattleground': 'JOIN BATTLEGROUND',
    'tacticalIntel': 'Tactical Intel',
    'closesIn': 'CLOSES IN',
    'matchLive': 'MATCH LIVE - JOINED PLAYERS',
    'matchFull': 'MATCH FULL - SLOTS CLOSED',
    'soloInstruction': 'Solo Mode: 48 members total. Only 1 member per entry. When 48 slots are filled, no other members can join.',
    'duoInstruction': 'Duo/Dot Mode: 24 teams (48 players). 2 members per team. When 24 teams join, no other members can join.',
    'squadInstruction': 'Squad Mode: 12 teams (48 players). 4 members per team. When 12 teams join, no other members can join.',
    'settings': 'Settings',
    'accountSecurity': 'Account Security',
    'paymentMethods': 'Payment Methods',
    'notifications': 'Notifications',
    'languageRegion': 'Language & Region',
    'appearance': 'Appearance',
    'helpCenter': 'Help Center',
    'logout': 'Logout',
    'matchesWon': 'Matches Won',
    'matchesLost': 'Matches Lost',
    'battleBuddy': 'Battle Buddy',
    'connections': 'Connections',
    'viewAll': 'View All',
    'editProfile': 'Edit Profile',
    'fullName': 'Full Name',
    'username': 'Username',
    'updateProfile': 'UPDATE PROFILE',
    'linkedAccounts': 'My Linked Accounts',
    'linkNew': 'LINK NEW ACCOUNT',
    'selectGateway': 'Select Gateway',
    'quickAmount': 'Quick Amount',
    'customAmount': 'Custom Amount',
    'addFunds': 'ADD FUNDS NOW',
    'withdrawWinnings': 'Withdraw Winnings',
    'requestWithdrawal': 'REQUEST WITHDRAWAL',
    'recentActivity': 'Recent Activity',
    'noActivity': 'No recent activity',
    'transactionHistory': 'Transaction History',
    'userId': 'USER ID',
    'confirmSelection': 'CONFIRM SELECTION',
    'savePreferences': 'SAVE PREFERENCES',
    'startTime': 'STARTS AT',
    'recentWinners': 'Recent Winners',
    'hallOfFame': 'Hall of Fame',
    'won': 'WON',
    'topParticipants': 'Top Participants',
    'mostActivePlayers': 'Most Active Players',
    'played': 'PLAYED',
    'joinedCount': 'Joined',
    'noLiveMatches': 'No live or upcoming matches at the moment.',
    'liveMatches': 'Live Matches',
    'currentlyActiveArenas': 'Currently Active Gaming Arenas',
    'matchHistory': 'Match History',
    'noMatchesYet': 'No Matches Yet',
    'joinUpcomingHistory': 'Join an upcoming match to see your history here.',
    'upcoming': 'UPCOMING',
    'inProgress': 'IN PROGRESS',
    'victory': 'VICTORY',
    'defeated': 'DEFEATED',
    'waiting': 'Waiting...',
    'calculating': 'Calculating...',
    'startsIn': 'Starts in:',
    'endsAt': 'Ends at:',
    'winnings': 'Winnings',
    'resetData': 'RESET DATA',
    'officialBroadcast': 'OFFICIAL BROADCAST',
    'liveMatchesNow': 'LIVE MATCHES NOW',
    'confirmDeposit': 'Confirm Deposit',
    'txnIdRequired': 'Transaction ID (Required)',
    'enterTxnId': 'Enter TXN ID from your payment',
    'confirmAddNow': 'CONFIRM & ADD NOW',
    'cancel': 'Cancel',
    'cancelGoBack': 'Cancel and go back',
    'proceedConfirm': 'PROCEED TO CONFIRM',
    'totalBalance': 'Total Balance',
    'myWallet': 'My Wallet',
    'addNew': 'Add New',
    'linkNewAccount': 'Link New Account',
    'activity': 'Activity',
    'personal': 'Personal',
    'community': 'Community',
    'onboardingSlide1Title': 'Ready to\\nPlace Bids?',
    'onboardingSlide1Desc': 'Lock your target, place your bid, and dominate the Free Fire battlefield. Swipe to learn more.',
    'onboardingSlide2Title': 'Choose Your\\nFF Squad',
    'onboardingSlide2Desc': 'Choose your favourite Free Fire team, back them with confidence, and watch them conquer Bermuda.',
    'onboardingSlide3Title': 'Claim Your\\nVictory',
    'onboardingSlide3Desc': 'Win big rewards when your Free Fire squad takes the Booyah! Your glory awaits.',
    'skip': 'Skip',
    'next': 'Next',
    'letsStart': "Let's Start",
    'welcomeBack': 'Welcome Back',
    'joinTheElite': 'Join the Elite',
    'loginSub': 'Enter your email and password to jump back into the action.',
    'registerSub': 'Experience the thrill of elite competitive gaming with Jxm Tour Club.',
    'ageCertification': 'I certify that I am 18 years of age or older, and agree to the Terms of Service.',
    'loginNow': 'Login Now',
    'registerAccount': 'Register Account',
    'processing': 'Processing...',
    'enterEmailPass': 'Please enter both email and password.',
    'agreeTerms': 'You must agree to the Terms of Service to register.',
    'enterName': 'Please enter your name.',
    'emailAddress': 'Email Address',
    'finalWinners': 'Final Winners',
    'joinedSuccessfully': 'Joined Successfully!',
    'dismiss': 'Dismiss',
    'continue': 'Continue',
    'gameIdName': 'Game ID Name',
    'enterGameIdName': 'Enter Game ID Name',
    'yourBalance': 'Your Balance',
    'selectTeam': 'Select Team',
    'winPrize': 'Win Prize',
    'perKill': 'Per Kill',
    'map': 'Map',
    'version': 'Version',
    'rule': 'Rule',
    'gameId': 'Game ID',
    'support': 'Support',
    'matchRules': 'Match Rules',
    'gameRoomId': 'Game Room ID',
    'joinRequiredForRoom': 'You must join this match to get access to the Room ID and Password.',
    'roomIdRevealMsgPrefix': 'Room ID and Password will be revealed ',
    'roomIdRevealMsgSuffix': ' minutes before the match begins.',
    'roomId': 'Room ID',
    'matchDiscussion': 'Match Discussion',
    'discussSub': 'Discuss strategies and gameplay live',
    'typeMessage': 'Type your message...',
    'cardNotFound': 'Card Not Found',
    'cardNotFoundDesc': "The match card you're looking for doesn't exist.",
    'goBack': 'Go Back',
    'confirmVia': 'Confirm via',
    'confirmDeletion': 'Confirm Deletion',
    'confirmDeleteDesc': 'Are you sure you want to remove this linked account? This action cannot be undone.',
    'deleteNow': 'Delete Now',
    'confirmWithdrawal': 'Confirm Withdrawal',
    'selectProvider': 'Select Provider',
    'enterAccountNumber': 'Enter account number',
    'withdrawAmount': 'Withdraw amount',
    'instructions': 'Instructions',
    'sendMoneyTo': 'Send Money To (Personal)',
    'binanceAddress': 'Binance Wallet Address',
    'copy': 'Copy',
    'noPersonalTx': 'No personal transactions yet.',
    'waitASecond': 'Wait a Second!',
    'removePaymentMethodDesc': 'Are you sure you want to remove this payment method? You will need to link it again for future withdrawals.',
    'yesRemoveIt': 'Yes, remove it',
    'keepMethod': 'Keep Method',
    'currencyPreference': 'Currency Preference',
    'helpCenterDesc': 'Find answers or contact our support team.',
    'needMoreHelp': 'Need more help?',
    'supportTeamDesc': 'Our support team is available 24/7 to assist you with any issues.',
    'chatWithUs': 'Chat with us',
    'faqTitle': 'Frequently Asked Questions',
    'closeCenter': 'Close Center',
    'depositRequested': 'Deposit Requested!',
    'depositRequestedDesc': 'Deposit request submitted! Balance will update after admin approval.',
    'withdrawalRequested': 'Withdrawal Requested!',
    'withdrawalRequestedDesc': 'Your withdrawal request has been submitted. Your balance has been updated and the request will be processed by the admin.',
    'insufficientBalance': 'Insufficient Balance',
    'insufficientBalanceDesc': "You don't have enough funds to complete this transaction. Let's top up your wallet.",
    'requiredFee': 'Required Fee:',
    'shortfall': 'Shortfall:',
    'quickDepositNow': 'Quick Deposit Now',
    'quickDeposit': 'Quick Deposit',
    'amountToAdd': 'Amount to Add',
    'submitDepositRequest': 'Submit Deposit Request',
    'requestSent': 'Request Sent!',
    'depositRequestSentPrefix': 'Your deposit request for ',
    'depositRequestSentSuffix': ' has been submitted. Balance will update once approved by admin.',
    'congratulations': 'Congratulations!',
    'liveSupport': 'Live Support',
    'onlineSupportAgent': 'Online Support Agent',
    'alwaysOnline': 'Always Online',
    'typeMessageHere': 'Type your message here...',
    'todaysUpcomingMatches': "Today's Upcoming Matches",
    'noMatchesToday': 'No matches scheduled for today.',
    'enterLobby': 'Enter Lobby',
    'victoryCeremony': 'Victory Ceremony',
    'matchComplete': 'Match Complete!',
    'ultimateChampion': 'Ultimate Champion',
    'eliteRunnerUp': 'Elite Runner Up',
    'bronzeContender': 'Bronze Contender',
    'claimed': 'Claimed',
    'dismissCeremony': 'Dismiss Ceremony'
  },
  bn: {
    'home': 'হোম',
    'wallet': 'ওয়ালেট',
    'myBets': 'ইতিহাস',
    'profile': 'প্রোফাইল',
    'live': 'লাইভ',
    'join': 'যোগ দিন',
    'joinNow': 'এখনই যোগ দিন',
    'totalPlayers': 'মোট খেলোয়াড়',
    'prizePool': 'প্রাইজ পুল',
    'entryFee': 'এন্ট্রি ফি',
    'matchDetails': 'ম্যাচের বিবরণ',
    'login': 'লগইন',
    'register': 'রেজিস্টার',
    'balance': 'ব্যালেন্স',
    'deposit': 'জমা করুন',
    'withdraw': 'উত্তোলন',
    'gamingArena': 'গেমিং এরিনা',
    'arenaSub': 'ম্যাচে যোগ দিন এবং পুরস্কার জিতুন',
    'active': 'সক্রিয়',
    'completed': 'সম্পন্ন',
    'history': 'ইতিহাস',
    'details': 'বিস্তারিত',
    'confirmEntry': 'আপনার এন্ট্রি নিশ্চিত করুন',
    'success': 'সফল',
    'joined': 'যোগদান করেছেন!',
    'language': 'ভাষা',
    'selectLanguage': 'ভাষা নির্বাচন করুন',
    'players': 'খেলোয়াড়',
    'entry': 'এন্ট্রি',
    'slotsOccupied': 'স্লট দখল করা হয়েছে',
    'capacity': 'ক্ষমতা',
    'fullHouse': 'ফুল হাউস',
    'joinBattleground': 'ব্যাটলগ্রাউন্ডে যোগ দিন',
    'tacticalIntel': 'কৌশলগত তথ্য',
    'closesIn': 'বন্ধ হবে:',
    'matchLive': 'ম্যাচ লাইভ - অংশগ্রহণকারী খেলোয়াড়',
    'matchFull': 'ম্যাচ পূর্ণ - স্লট বন্ধ',
    'soloInstruction': 'সোলো মোড: মোট ৪৮ জন সদস্য। প্রতি এনট্রিতে মাত্র ১ জন সদস্য। ৪৮টি স্লট পূর্ণ হলে অন্য কেউ যোগ দিতে পারবে না।',
    'duoInstruction': 'ডুও মোড: ২৪টি দল (৪৮ জন খেলোয়াড়)। প্রতি দলে ২ জন সদস্য। ২৪টি দল যোগ দিলে অন্য কেউ যোগ দিতে পারবে না।',
    'squadInstruction': 'স্কোয়াড মোড: ১২টি দল (৪৮ জন খেলোয়াড়)। প্রতি দলে ৪ জন সদস্য। ১২টি দল যোগ দিলে অন্য কেউ যোগ দিতে পারবে না।',
    'settings': 'সেটিংস',
    'accountSecurity': 'অ্যাকাউন্ট নিরাপত্তা',
    'paymentMethods': 'পেমেন্ট পদ্ধতি',
    'notifications': 'নোটিফিকেশন',
    'languageRegion': 'ভাষা ও অঞ্চল',
    'appearance': 'চেহারা',
    'helpCenter': 'হেল্প সেন্টার',
    'logout': 'লগআউট',
    'matchesWon': 'ম্যাচ জয়ী',
    'matchesLost': 'ম্যাচ পরাজিত',
    'battleBuddy': 'ব্যাটল বাডি',
    'connections': 'কানেকশন',
    'viewAll': 'সব দেখুন',
    'editProfile': 'প্রোফাইল এডিট করুন',
    'fullName': 'পুরো নাম',
    'username': 'ব্যবহারকারীর নাম',
    'updateProfile': 'প্রোফাইল আপডেট করুন',
    'linkedAccounts': 'আমার লিঙ্ক করা অ্যাকাউন্ট',
    'linkNew': 'নতুন অ্যাকাউন্ট লিঙ্ক করুন',
    'selectGateway': 'গেটওয়ে নির্বাচন করুন',
    'quickAmount': 'দ্রুত পরিমাণ',
    'customAmount': 'কাস্টম পরিমাণ',
    'addFunds': 'এখনই টাকা যোগ করুন',
    'withdrawWinnings': 'জেতা টাকা উত্তোলন',
    'requestWithdrawal': 'উত্তোলনের অনুরোধ করুন',
    'recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'noActivity': 'কোন সাম্প্রতিক কার্যক্রম নেই',
    'transactionHistory': 'লেনদেনের ইতিহাস',
    'userId': 'ইউজার আইডি',
    'confirmSelection': 'নির্বাচন নিশ্চিত করুন',
    'savePreferences': 'পছন্দগুলি সংরক্ষণ করুন',
    'startTime': 'শুরু হবে',
    'recentWinners': 'সাম্প্রতিক বিজয়ী',
    'hallOfFame': 'হল অব ফেম',
    'won': 'জয়ী',
    'topParticipants': 'সেরা অংশগ্রহণকারী',
    'mostActivePlayers': 'সবচেয়ে সক্রিয় খেলোয়াড়',
    'played': 'খেলেছেন',
    'joinedCount': 'অংশগ্রহণকারী',
    'noLiveMatches': 'এই মুহূর্তে কোনো লাইভ বা আসন্ন ম্যাচ নেই।',
    'liveMatches': 'লাইভ ম্যাচ',
    'currentlyActiveArenas': 'বর্তমানে সক্রিয় গেমিং এরিনা',
    'matchHistory': 'ম্যাচের ইতিহাস',
    'noMatchesYet': 'এখনো কোনো ম্যাচ নেই',
    'joinUpcomingHistory': 'আপনার ইতিহাস এখানে দেখতে একটি আসন্ন ম্যাচে যোগ দিন।',
    'upcoming': 'আসন্ন',
    'inProgress': 'চলমান',
    'victory': 'বিজয়',
    'defeated': 'পরাজিত',
    'waiting': 'অপেক্ষা করা হচ্ছে...',
    'calculating': 'হিসাব করা হচ্ছে...',
    'startsIn': 'শুরু হবে:',
    'endsAt': 'শেষ হবে:',
    'winnings': 'জিতের পরিমাণ',
    'resetData': 'ডাটা রিসেট করুন',
    'officialBroadcast': 'অফিসিয়াল ব্রডকাস্ট',
    'liveMatchesNow': 'এখন লাইভ ম্যাচ',
    'confirmDeposit': 'জমা নিশ্চিত করুন',
    'txnIdRequired': 'ট্রানজেকশন আইডি (প্রয়োজন)',
    'enterTxnId': 'আপনার পেমেন্টের TXN আইডি লিখুন',
    'confirmAddNow': 'নিশ্চিত করুন এবং যোগ করুন',
    'cancel': 'বাতিল করুন',
    'cancelGoBack': 'বাতিল করুন এবং ফিরে যান',
    'proceedConfirm': 'নিশ্চিত করতে এগিয়ে যান',
    'totalBalance': 'মোট ব্যালেন্স',
    'myWallet': 'আমার ওয়ালেট',
    'addNew': 'নতুন যোগ করুন',
    'linkNewAccount': 'নতুন অ্যাকাউন্ট লিঙ্ক করুন',
    'activity': 'কার্যক্রম',
    'personal': 'ব্যক্তিগত',
    'community': 'কমিউনিটি',
    'onboardingSlide1Title': 'বিড করার জন্য\\nপ্রস্তুত?',
    'onboardingSlide1Desc': 'আপনার লক্ষ্য নির্ধারণ করুন, বিড করুন এবং ফ্রি ফায়ার যুদ্ধক্ষেত্রে আধিপত্য বিস্তার করুন। আরও জানতে সোয়াইপ করুন।',
    'onboardingSlide2Title': 'আপনার ফ্রি ফায়ার\\nস্কোয়াড নির্বাচন করুন',
    'onboardingSlide2Desc': 'আপনার প্রিয় ফ্রি ফায়ার দল বেছে নিন, আত্মবিশ্বাসের সাথে তাদের সমর্থন করুন এবং তাদের বারমুডা জয় করতে দেখুন।',
    'onboardingSlide3Title': 'আপনার বিজয়\\nদাবি করুন',
    'onboardingSlide3Desc': 'আপনার ফ্রি ফায়ার স্কোয়াড বুয়াহ (Booyah) নিলে বড় পুরস্কার জিতুন! আপনার গৌরব অপেক্ষা করছে।',
    'skip': 'এড়িয়ে যান',
    'next': 'পরবর্তী',
    'letsStart': 'শুরু করা যাক',
    'welcomeBack': 'স্বাগতম',
    'joinTheElite': 'এলিটদের সাথে যোগ দিন',
    'loginSub': 'আবারও লড়াইয়ে অংশ নিতে আপনার ইমেল এবং পাসওয়ার্ড লিখুন।',
    'registerSub': 'জেএক্সএম ট্যুর ক্লাবের সাথে গেমিংয়ের রোমাঞ্চ অনুভব করুন।',
    'ageCertification': 'আমি প্রত্যয়িত করছি যে আমার বয়স ১৮ বছর বা তার বেশি এবং আমি পরিষেবার শর্তাবলীতে সম্মত।',
    'loginNow': 'এখনই লগইন করুন',
    'registerAccount': 'অ্যাকাউন্ট রেজিস্টার করুন',
    'processing': 'প্রক্রিয়াধীন...',
    'enterEmailPass': 'অনুগ্রহ করে ইমেল এবং পাসওয়ার্ড উভয়ই লিখুন।',
    'agreeTerms': 'রেজিস্টার করতে আপনাকে অবশ্যই পরিষেবার শর্তাবলীতে সম্মত হতে হবে।',
    'enterName': 'অনুগ্রহ করে আপনার নাম লিখুন।',
    'emailAddress': 'ইমেল ঠিকানা',
    'finalWinners': 'চূড়ান্ত বিজয়ী',
    'joinedSuccessfully': 'সফলভাবে যোগদান করেছেন!',
    'dismiss': 'খারিজ করুন',
    'continue': 'চালিয়ে যান',
    'gameIdName': 'গেম আইডি নাম',
    'enterGameIdName': 'গেম আইডি নাম লিখুন',
    'yourBalance': 'আপনার ব্যালেন্স',
    'selectTeam': 'দল নির্বাচন করুন',
    'winPrize': 'জিতের পুরস্কার',
    'perKill': 'প্রতি কিল',
    'map': 'ম্যাপ',
    'version': 'ভার্সন',
    'rule': 'নিয়ম',
    'gameId': 'গেম আইডি',
    'support': 'সাপোর্ট',
    'matchRules': 'ম্যাচের নিয়মাবলী',
    'gameRoomId': 'গেম রুম আইডি',
    'joinRequiredForRoom': 'রুম আইডি এবং পাসওয়ার্ড পেতে আপনাকে অবশ্যই এই ম্যাচে যোগ দিতে হবে।',
    'roomIdRevealMsgPrefix': 'Room ID and Password will be revealed ',
    'roomIdRevealMsgSuffix': ' minutes before the match begins.',
    'roomId': 'Room ID',
    'matchDiscussion': 'ম্যাচ আলোচনা',
    'discussSub': 'কৌশল এবং গেমপ্লে লাইভ আলোচনা করুন',
    'typeMessage': 'Type your message...',
    'cardNotFound': 'কার্ড পাওয়া যায়নি',
    'cardNotFoundDesc': 'আপনি যে ম্যাচ কার্ডটি খুঁজছেন তা বিদ্যমান নেই।',
    'goBack': 'ফিরে যান',
    'confirmVia': 'এর মাধ্যমে নিশ্চিত করুন',
    'confirmDeletion': 'মুছে ফেলার নিশ্চিতকরণ',
    'confirmDeleteDesc': 'আপনি কি নিশ্চিত যে আপনি এই লিঙ্ক করা অ্যাকাউন্টটি সরাতে চান? এই কাজটি আর ফিরিয়ে আনা যাবে না।',
    'deleteNow': 'এখনই মুছে ফেলুন',
    'confirmWithdrawal': 'উত্তোলন নিশ্চিত করুন',
    'selectProvider': 'প্রোভাইডার নির্বাচন করুন',
    'enterAccountNumber': 'অ্যাকাউন্ট নম্বর লিখুন',
    'withdrawAmount': 'উত্তোলনের পরিমাণ',
    'instructions': 'নির্দেশাবলী',
    'sendMoneyTo': 'টাকা পাঠান (পার্সোনাল)',
    'binanceAddress': 'বাইনান্স ওয়ালেট এড্রেস',
    'copy': 'কপি',
    'noPersonalTx': 'এখনো কোনো ব্যক্তিগত লেনদেন নেই।',
    'waitASecond': 'এক সেকেন্ড অপেক্ষা করুন!',
    'removePaymentMethodDesc': 'আপনি কি নিশ্চিত যে আপনি এই পেমেন্ট পদ্ধতিটি সরাতে চান? ভবিষ্যতের উত্তোলনের জন্য আপনাকে এটি আবার লিঙ্ক করতে হবে।',
    'yesRemoveIt': 'হ্যাঁ, এটি সরিয়ে দিন',
    'keepMethod': 'পদ্ধতিটি রাখুন',
    'currencyPreference': 'মুদ্রা পছন্দ',
    'helpCenterDesc': 'উত্তর খুঁজুন বা আমাদের সাপোর্ট টিমের সাথে যোগাযোগ করুন।',
    'needMoreHelp': 'আরও সাহায্য প্রয়োজন?',
    'supportTeamDesc': 'যেকোনো সমস্যায় আপনাকে সাহায্য করার জন্য আমাদের সাপোর্ট টিম ২৪/৭ উপলব্ধ।',
    'chatWithUs': 'আমাদের সাথে চ্যাট করুন',
    'faqTitle': 'সচরাচর জিজ্ঞাসিত প্রশ্নাবলী',
    'closeCenter': 'সাপোর্ট সেন্টার বন্ধ করুন',
    'depositRequested': 'জমার অনুরোধ জমা পড়েছে!',
    'depositRequestedDesc': 'জমার অনুরোধ জমা দেওয়া হয়েছে! এডমিনের অনুমোদনের পর ব্যালেন্স আপডেট হবে।',
    'withdrawalRequested': 'উত্তোলনের অনুরোধ জমা পড়েছে!',
    'withdrawalRequestedDesc': 'আপনাদের উত্তোলনের অনুরোধ জমা দেওয়া হয়েছে। আপনাদের ব্যালেন্স আপডেট করা হয়েছে এবং এডমিন দ্বারা অনুরোধটি প্রক্রিয়া করা হবে।',
    'insufficientBalance': 'অপর্যাপ্ত ব্যালেন্স',
    'insufficientBalanceDesc': 'এই লেনদেনটি সম্পন্ন করার জন্য আপনার পর্যাপ্ত তহবিল নেই। আসুন আপনার ওয়ালেট টপ আপ করি।',
    'requiredFee': 'প্রয়োজনীয় ফি:',
    'shortfall': 'ঘাটতি:',
    'quickDepositNow': 'এখনই দ্রুত জমা করুন',
    'quickDeposit': 'দ্রুত জমা',
    'amountToAdd': 'যোগ করার পরিমাণ',
    'submitDepositRequest': 'জমার অনুরোধ জমা দিন',
    'requestSent': 'অনুরোধ পাঠানো হয়েছে!',
    'depositRequestSentPrefix': 'আপনার ',
    'depositRequestSentSuffix': ' জমার অনুরোধ পাঠানো হয়েছে। এডমিন অনুমোদন করলে ব্যালেন্স আপডেট হবে।',
    'congratulations': 'অভিনন্দন!',
    'liveSupport': 'লাইভ সাপোর্ট',
    'onlineSupportAgent': 'অনлайн সাপোর্ট এজেন্ট',
    'alwaysOnline': 'সবসময় অনলাইন',
    'typeMessageHere': 'আপনার বার্তাটি এখানে লিখুন...',
    'todaysUpcomingMatches': 'আজকের আসন্ন ম্যাচসমূহ',
    'noMatchesToday': 'আজকের জন্য কোনো ম্যাচ নির্ধারিত নেই।',
    'enterLobby': 'লবিতে প্রবেশ করুন',
    'victoryCeremony': 'বিজয় উৎসব',
    'matchComplete': 'ম্যাচ সম্পন্ন!',
    'ultimateChampion': 'পরম চ্যাম্পিয়ন',
    'eliteRunnerUp': 'এলিট রানার আপ',
    'bronzeContender': 'ব্রোঞ্জ প্রতিযোগী',
    'claimed': 'দাবি করা হয়েছে',
    'dismissCeremony': 'উৎসব বন্ধ করুন'
  },
  hi: {
    'home': 'होम',
    'wallet': 'वॉलेट',
    'myBets': 'इतिहास',
    'profile': 'प्रोफाइल',
    'live': 'लाइव',
    'join': 'शामिल हों',
    'joinNow': 'अभी शामिल हों',
    'totalPlayers': 'कुल खिलाड़ी',
    'prizePool': 'प्राइज़ पूल',
    'entryFee': 'एंट्री फीस',
    'matchDetails': 'मैच विवरण',
    'login': 'लॉगिन',
    'register': 'रजिस्टर',
    'balance': 'बैलेंस',
    'deposit': 'जमा करें',
    'withdraw': 'निकासी',
    'gamingArena': 'गेमिंग एरिना',
    'arenaSub': 'मैचों में शामिल हों और पुरस्कार जीतें',
    'active': 'सक्रिय',
    'completed': 'पूरा हुआ',
    'history': 'इतिहास',
    'details': 'विवरण',
    'confirmEntry': 'अपनी प्रविष्टि की पुष्टि करें',
    'success': 'सफल',
    'joined': 'शामिल हो गए!',
    'language': 'भाषा',
    'selectLanguage': 'भाषा चुनें',
    'players': 'खिलाड़ी',
    'entry': 'एंट्री',
    'slotsOccupied': 'स्लॉट भरे हुए हैं',
    'capacity': 'क्षमता',
    'fullHouse': 'हाउस फुल',
    'joinBattleground': 'मैदान में उतरें',
    'tacticalIntel': 'रणनीतिक जानकारी',
    'closesIn': 'समाप्ति समय:',
    'matchLive': 'मैच लाइव - खिलाड़ी शामिल हैं',
    'matchFull': 'मैच फुल - स्लॉट बंद',
    'soloInstruction': 'सोलो मोड: कुल 48 सदस्य। प्रति प्रविष्टि केवल 1 सदस्य। 48 स्लॉट भरने पर कोई अन्य सदस्य शामिल नहीं हो सकता।',
    'duoInstruction': 'दुओ मोड: 24 टीमें (48 खिलाड़ी)। प्रति टीम 2 सदस्य। 24 टीमें शामिल होने पर कोई अन्य सदस्य शामिल नहीं हो सकता।',
    'squadInstruction': 'स्कवाद मोड: 12 टीमें (48 खिलाड़ी)। प्रति टीम 4 सदस्य। 12 टीमें शामिल होने पर कोई अन्य सदस्य शामिल नहीं हो सकता।',
    'settings': 'सेटिंग्स',
    'accountSecurity': 'अकाउंट सुरक्षा',
    'paymentMethods': 'भुगतान विधियां',
    'notifications': 'नोटिफिकेशन',
    'languageRegion': 'भाषा और क्षेत्र',
    'appearance': 'रंग-रूप',
    'helpCenter': 'सहायता केंद्र',
    'logout': 'लॉगआउट',
    'matchesWon': 'मैच जीते',
    'matchesLost': 'मैच हारे',
    'battleBuddy': 'बैटल बडी',
    'connections': 'कनेक्शन',
    'viewAll': 'सभी देखें',
    'editProfile': 'प्रोफ़ाइल संपादित करें',
    'fullName': 'पूरा नाम',
    'username': 'यूज़रनेम',
    'updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'linkedAccounts': 'मेरे लिंक किए गए अकाउंट',
    'linkNew': 'नया अकाउंट लिंक करें',
    'selectGateway': 'गेटवे चुनें',
    'quickAmount': 'त्वरित राशि',
    'customAmount': 'कस्टम राशि',
    'addFunds': 'अभी फंड जोड़ें',
    'withdrawWinnings': 'जीत की निकासी',
    'requestWithdrawal': 'निकासी का अनुरोध करें',
    'recentActivity': 'हाल की गतिविधि',
    'noActivity': 'कोई हाल की गतिविधि नहीं',
    'transactionHistory': 'लेनदेन का इतिहास',
    'userId': 'यूज़र आईडी',
    'confirmSelection': 'चयन की पुष्टि करें',
    'savePreferences': 'पसंद सहेजें',
    'startTime': 'शुरू होगा'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = (key: string, params?: Record<string, string>) => {
    let text = translations[language][key] || translations['en'][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
