import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'bn' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'home': 'Home',
    'wallet': 'Wallet',
    'myBets': 'History',
    'profile': 'Profile',
    'live': 'Live',
    'join': 'Join',
    'joinNow': 'JOIN MATCH NOW',
    'totalPlayers': 'Total Players',
    'prizePool': 'Prize Pool',
    'entryFee': 'Entry Fee',
    'matchDetails': 'Match Details',
    'login': 'Login',
    'register': 'Register',
    'balance': 'Balance',
    'deposit': 'Deposit',
    'withdraw': 'Withdraw',
    'gamingArena': 'Gaming Arena',
    'arenaSub': 'Join matches & earn rewards',
    'active': 'Active',
    'completed': 'Completed',
    'history': 'History',
    'details': 'Details',
    'confirmEntry': 'Confirm Your Entry',
    'success': 'Success',
    'joined': 'Joined!',
    'language': 'Language',
    'selectLanguage': 'Select Language',
    'players': 'Players',
    'entry': 'Entry',
    'slotsOccupied': 'Slots Occupied',
    'capacity': 'CAPACITY',
    'fullHouse': 'FULL HOUSE',
    'joinBattleground': 'JOIN BATTLEGROUND',
    'tacticalIntel': 'Tactical Intel',
    'closesIn': 'CLOSES IN',
    'matchLive': 'MATCH LIVE - JOINED PLAYERS',
    'matchFull': 'MATCH FULL - SLOTS CLOSED',
    'soloInstruction': 'Solo Mode: 48 members total. Only 1 member per entry. When 48 slots are filled, no other members can join.',
    'duoInstruction': 'Duo/Dot Mode: 24 teams (48 players). 2 members per team. When 24 teams join, no other members can join.',
    'squadInstruction': 'Squad Mode: 12 teams (48 players). 4 members per team. When 12 teams join, no other members can join.',
    'settings': 'Settings',
    'accountSecurity': 'Account Security',
    'paymentMethods': 'Payment Methods',
    'notifications': 'Notifications',
    'languageRegion': 'Language & Region',
    'appearance': 'Appearance',
    'helpCenter': 'Help Center',
    'logout': 'Logout',
    'matchesWon': 'Matches Won',
    'played': 'Played',
    'matchFound': 'Match Found',
    'matchesFound': 'Matches Found',
    'totalJoiningMatch': 'Community',
    'battleBuddy': 'Battle Buddy',
    'connections': 'Connections',
    'viewAll': 'View All',
    'editProfile': 'Edit Profile',
    'fullName': 'Full Name',
    'username': 'Username',
    'updateProfile': 'UPDATE PROFILE',
    'linkedAccounts': 'My Linked Accounts',
    'linkNew': 'LINK NEW ACCOUNT',
    'selectGateway': 'Select Gateway',
    'quickAmount': 'Quick Amount',
    'customAmount': 'Custom Amount',
    'addFunds': 'ADD FUNDS NOW',
    'withdrawWinnings': 'Withdraw Winnings',
    'requestWithdrawal': 'REQUEST WITHDRAWAL',
    'recentActivity': 'Recent Activity',
    'noActivity': 'No recent activity',
    'transactionHistory': 'Transaction History',
    'userId': 'USER ID',
    'confirmSelection': 'CONFIRM SELECTION',
    'savePreferences': 'SAVE PREFERENCES',
    'startTime': 'STARTS AT',
    'liveMatches': 'Live Matches',
    'participants': 'Participants',
    'winnersCount': 'Winners',
    'addFundsTitle': 'Add Funds',
    'customAmountLabel': 'Custom Amount',
    'confirmDeposit': 'Confirm Deposit',
    'confirmAndAddNow': 'CONFIRM & ADD NOW',
    'cancelGoBack': 'Cancel and go back',
    'noMatchesJoined': 'No Matches Joined',
    'joinedOn': 'Joined on',
    'minimumDeposit': 'Minimum Deposit',
    'minimumWithdraw': 'Minimum Withdraw',
    'officialBroadcast': 'OFFICIAL BROADCAST',
    'liveMatchesNow': 'LIVE MATCHES NOW',
    'upcomingMatches': "TODAY'S UPCOMING MATCHES",
    'noMatchesScheduled': 'No matches scheduled for today.',
    'enterLobby': 'Enter Lobby',
    'txnIdRequired': 'Transaction ID (Required)',
    'enterTxnId': 'Enter TXN ID from your payment',
    'insufficientBalance': 'Insufficient Balance',
    'requiredAmount': 'Required Amount',
    'topUpNow': 'TOP UP NOW',
    'myLinkedAccounts': 'My Linked Accounts',
    'addNew': 'Add New',
    'selectLinkedAccount': 'Select a linked account to receive your winnings.',
    'withdrawAmount': 'Withdraw amount',
    'max': 'MAX',
    'personal': 'Personal',
    'community': 'Community',
    'noTransactions': 'No personal transactions yet.',
    'activity': 'Activity',
    'confirmVia': 'Confirm via',
    'confirmWithdrawal': 'Confirm Withdrawal',
    'linkAccountTitle': 'Link Account',
    'linkAccountSub': 'Link your Bkash, Nagad or Binance for quick payments.',
    'selectProvider': 'Select Provider',
    'enterAccountNumber': 'Enter account number',
    'linkAccountBtn': 'LINK ACCOUNT',
    'cancel': 'Cancel',
    'confirmDeletion': 'Confirm Deletion',
    'deleteConfirmationMsg': 'Are you sure you want to remove this linked account? This action cannot be undone.',
    'deleteNow': 'DELETE NOW',
    'victory': 'Victory',
    'matchEnded': 'Match Ended',
    'finalPrize': 'Final Prize',
    'winnings': 'Winnings',
    'depositRequestSent': 'Deposit Request Sent!',
    'depositSentSub': 'deposit request has been sent for admin approval.',
    'proceedToConfirm': 'PROCEED TO CONFIRM',
    'addingFundsPrefix': 'You are adding',
    'addingFundsSuffix': 'to your secure wallet.',
    'withdrawingFundsPrefix': 'You are requesting to withdraw',
    'withdrawingFundsSuffix': 'to your',
    'account': 'account',
    'notificationSettingsSub': 'Control how you receive alerts and updates.',
    'pushNotifications': 'Push Notifications',
    'pushNotificationsDesc': 'Alerts for matches and tournaments',
    'emailAlerts': 'Email Alerts',
    'emailAlertsDesc': 'Updates about your account and wallet',
    'tournamentUpdates': 'Tournament Updates',
    'tournamentUpdatesDesc': 'New features and event announcements',
    'selectLanguageSub': 'Select your preferred language for the interface.',
    'langEnglish': 'English',
    'regionUS': 'United States',
    'langBengali': 'Bengali',
    'regionBD': 'Bangladesh',
    'langHindi': 'Hindi',
    'regionIN': 'India',
    'helpCenterSub': 'Find answers or contact our support team.',
    'needMoreHelp': 'Need more help?',
    'supportTeamAvailability': 'Our support team is available 24/7 to assist you with any issues.',
    'chatWithUs': 'CHAT WITH US',
    'faqTitle': 'Frequently Asked Questions',
    'faq1q': 'How do I join a match?',
    'faq1a': 'Go to the Home screen, select a tournament, and click Join. Make sure you have enough balance!',
    'faq2q': 'When will I get my winnings?',
    'faq2a': 'Winnings are usually credited within 1-2 hours after the match ends.',
    'faq3q': 'What are the withdrawal limits?',
    'faq3a': 'Minimum withdrawal is 50 BDT and maximum is 50,000 BDT per day.',
    'faq4q': 'Is my data secure?',
    'faq4a': 'Yes, we use enterprise-grade encryption to protect all your personal and financial data.',
    'closeCenter': 'CLOSE CENTER',
    'waitASec': 'Wait a Second!',
    'deleteMethodWarn': 'Are you sure you want to remove this payment method? You will need to link it again for future withdrawals.',
    'yesRemoveIt': 'YES, REMOVE IT',
    'keepMethod': 'Keep Method',
    'currencyPreference': 'Currency Preference',
    'enterAmount': 'Enter amount',
    'finalWinners': 'Final Winners',
    'joinNowWithBet': 'Join Now',
    'bettingTeam': 'Betting Team',
    'gameIdName': 'Game ID Name',
    'enterGameIdName': 'Enter Game ID Name',
    'joinedSuccessfully': 'Joined Successfully!',
    'dismiss': 'Dismiss',
    'matchNotFound': 'Match not found',
    'arena': 'Arena',
    'ended': 'ENDED',
    'startIn': 'START IN',
    'noPaymentMethods': 'No payment methods available.',
    'rule': 'Rule',
    'gameId': 'Game ID',
    'support': 'Support',
    'matchRules': 'Match Rules',
    'gameRoomId': 'Game Room ID',
    'roomId': 'Room ID',
    'password': 'Password',
    'matchDiscussion': 'Match Discussion',
    'discussStrategies': 'Discuss strategies and gameplay live',
    'typeMessage': 'Type your message...',
    'winPrize': 'Win Prize',
    'perKill': 'Per Kill',
    'map': 'Map',
    'version': 'Version',
    'yourBalance': 'Your Balance',
    'continue': 'Continue',
    'joinedPill': 'JOINED',
    'fullPill': 'FULL',
    'joinNowPill': 'JOIN NOW',
    'gameRoomIdSub': 'You must join this match to get access to the Room ID and Password.',
    'revealTimeMsgPrefix': 'Room ID and Password will be revealed',
    'revealTimeMsgSuffix': 'minutes before the match begins.',
    'pending': 'Pending...',
    'updating': 'Updating...',
    'match': 'Match',
    'matches': 'Matches',
    'shortfall': 'Shortfall',
    'requiredFee': 'Required Fee',
    'quickDepositNow': 'QUICK DEPOSIT NOW',
    'requestSent': 'Request Sent!',
    'quickDeposit': 'Quick Deposit',
    'amountToAdd': 'Amount to Add',
    'submitDepositRequest': 'SUBMIT DEPOSIT REQUEST',
    'back': 'Back',
    'insufficientBalanceSub': "You don't have enough funds to complete this transaction. Let's top up your wallet.",
    'depositSuccessSub': 'Your deposit request for {amount} has been submitted. Balance will update once approved by admin.',
    'awaitingCommunity': 'Awaiting community moves...',
    'player': 'A Player',
    'deposited': 'deposited',
    'withdrew': 'withdrew',
    'won': 'won',
    'in': 'in',
    'performedAction': 'performed an action',
    'highRoller': 'High Roller',
    'you': 'YOU',
    'obSkip': 'Skip',
    'obNext': 'Next',
    'obStart': "Let's Start",
    'obSlide1Title': 'Ready to\nPlace Bids?',
    'obSlide1Desc': 'Lock your target, place your bid, and dominate the Free Fire battlefield. Swipe to learn more.',
    'obSlide2Title': 'Choose Your\nFF Squad',
    'obSlide2Desc': 'Choose your favourite Free Fire team, back them with confidence, and watch them conquer Bermuda.',
    'obSlide3Title': 'Claim Your\nVictory',
    'obSlide3Desc': 'Win big rewards when your Free Fire squad takes the Booyah! Your glory awaits.',
    'welcomeBack': 'Welcome Back',
    'joinTheElite': 'Join the Elite',
    'loginSub': 'Enter your email and password to jump back into the action.',
    'registerSub': 'Experience the thrill of elite competitive gaming with Jxm Tour Club.',
    'emailAddress': 'Email Address',
    'termsAgreement': 'I certify that I am 18 years of age or older, and agree to the Terms of Service.',
    'loginNowBtn': 'Login Now',
    'registerAccountBtn': 'Register Account',
    'processing': 'Processing...',
    'enterEmailPassword': 'Please enter both email and password.',
    'agreeTermsWarn': 'You must agree to the Terms of Service to register.',
    'enterNameWarn': 'Please enter your name.',
    'registrationSuccess': 'Registration successful! Logging you in...',
    'emailInUse': 'This email is already registered.',
    'invalidCredentials': 'Invalid email or password.',
    'weakPassword': 'Password should be at least 6 characters.',
    'authFailed': 'Authentication failed. Please try again.',
    'victoryCeremony': 'Victory Ceremony',
    'matchComplete': 'MATCH COMPLETE!',
    'ultimateChampion': 'Ultimate Champion',
    'eliteRunnerUp': 'Elite Runner Up',
    'bronzeContender': 'Bronze Contender',
    'claimed': 'CLAIMED',
    'dismissCeremony': 'DISMISS CEREMONY',
    'assignedSlot': 'Assigned Slot',
    'slotNumber': 'Slot Number',
    'joinedEnd': 'JOINED END',
    'timeExpired': 'Time Expired',
    'idle': 'IDLE'
  },
  bn: {
    'home': 'হোম',
    'wallet': 'ওয়ালেট',
    'myBets': 'ইতিহাস',
    'profile': 'প্রোফাইল',
    'live': 'লাইভ',
    'join': 'যোগ দিন',
    'joinNow': 'এখনই যোগ দিন',
    'totalPlayers': 'মোট খেলোয়াড়',
    'prizePool': 'প্রাইজ পুল',
    'entryFee': 'এন্ট্রি ফি',
    'matchDetails': 'ম্যাচের বিবরণ',
    'login': 'লগইন',
    'register': 'রেজিস্টার',
    'balance': 'ব্যালেন্স',
    'deposit': 'জমা করুন',
    'withdraw': 'উত্তোলন',
    'gamingArena': 'গেমিং এরিনা',
    'arenaSub': 'ম্যাচে যোগ দিন এবং পুরস্কার জিতুন',
    'active': 'সক্রিয়',
    'completed': 'সম্পন্ন',
    'history': 'ইতিহাস',
    'details': 'বিস্তারিত',
    'confirmEntry': 'আপনার এন্ট্রি নিশ্চিত করুন',
    'success': 'সফল',
    'joined': 'যোগদান করেছেন!',
    'language': 'ভাষা',
    'selectLanguage': 'ভাষা নির্বাচন করুন',
    'players': 'খেলোয়াড়',
    'entry': 'এন্ট্রি',
    'slotsOccupied': 'স্লট দখল করা হয়েছে',
    'capacity': 'ক্ষমতা',
    'fullHouse': 'ফুল হাউস',
    'joinBattleground': 'ব্যাটলগ্রাউন্ডে যোগ দিন',
    'tacticalIntel': 'কৌশলগত তথ্য',
    'closesIn': 'বন্ধ হবে:',
    'matchLive': 'ম্যাচ লাইভ - অংশগ্রহণকারী খেলোয়াড়',
    'matchFull': 'ম্যাচ পূর্ণ - স্লট বন্ধ',
    'soloInstruction': 'সোলো মোড: মোট ৪৮ জন সদস্য। প্রতি এনট্রিতে মাত্র ১ জন সদস্য। ৪৮টি স্লট পূর্ণ হলে অন্য কেউ যোগ দিতে পারবে না।',
    'duoInstruction': 'ডুও মোড: ২৪টি দল (৪৮ জন খেলোয়াড়)। প্রতি দলে ২ জন সদস্য। ২৪টি দল যোগ দিলে অন্য কেউ যোগ দিতে পারবে না।',
    'squadInstruction': 'স্কোয়াড মোড: ১২টি দল (৪৮ জন খেলোয়াড়)। প্রতি দলে ৪ জন সদস্য। ১২টি দল যোগ দিলে অন্য কেউ যোগ দিতে পারবে না।',
    'settings': 'সেটিংস',
    'accountSecurity': 'অ্যাকাউন্ট নিরাপত্তা',
    'paymentMethods': 'পেমেন্ট পদ্ধতি',
    'notifications': 'নোটিফিকেশন',
    'languageRegion': 'ভাষা ও অঞ্চল',
    'appearance': 'চেহারা',
    'helpCenter': 'হেল্প সেন্টার',
    'logout': 'লগআউট',
    'matchesWon': 'ম্যাচ জয়ী',
    'played': 'খেলেছেন',
    'matchFound': 'টি ম্যাচ পাওয়া গেছে',
    'matchesFound': 'টি ম্যাচ পাওয়া গেছে',
    'totalJoiningMatch': 'কমিউনিটি',
    'battleBuddy': 'ব্যাটল বাডি',
    'connections': 'কানেকশন',
    'viewAll': 'সব দেখুন',
    'editProfile': 'প্রোফাইল এডিট করুন',
    'fullName': 'পুরো নাম',
    'username': 'ব্যবহারকারীর নাম',
    'updateProfile': 'প্রোফাইল আপডেট করুন',
    'linkedAccounts': 'আমার লিঙ্ক করা অ্যাকাউন্ট',
    'linkNew': 'নতুন অ্যাকাউন্ট লিঙ্ক করুন',
    'selectGateway': 'গেটওয়ে নির্বাচন করুন',
    'quickAmount': 'দ্রুত পরিমাণ',
    'customAmount': 'কাস্টম পরিমাণ',
    'addFunds': 'এখনই টাকা যোগ করুন',
    'withdrawWinnings': 'জেতা টাকা উত্তোলন',
    'requestWithdrawal': 'উত্তোলনের অনুরোধ করুন',
    'recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'noActivity': 'কোন সাম্প্রতিক কার্যক্রম নেই',
    'transactionHistory': 'লেনদেনের ইতিহাস',
    'userId': 'ইউজার আইডি',
    'confirmSelection': 'নির্বাচন নিশ্চিত করুন',
    'savePreferences': 'পছন্দগুলি সংরক্ষণ করুন',
    'startTime': 'শুরু হবে',
    'liveMatches': 'লাইভ ম্যাচ',
    'participants': 'অংশগ্রহণকারী',
    'winnersCount': 'বিজয়ী',
    'addFundsTitle': 'টাকা যোগ করুন',
    'customAmountLabel': 'কাস্টম পরিমাণ',
    'confirmDeposit': 'আমানত নিশ্চিত করুন',
    'confirmAndAddNow': 'নিশ্চিত করুন এবং যোগ করুন',
    'cancelGoBack': 'বাতিল করুন এবং ফিরে যান',
    'noMatchesJoined': 'কোন ম্যাচে যোগ দেননি',
    'joinedOn': 'যোগদানের তারিখ',
    'minimumDeposit': 'সর্বনিম্ন আমানত',
    'minimumWithdraw': 'সর্বনিম্ন উত্তোলন',
    'officialBroadcast': 'অফিসিয়াল ঘোষণা',
    'liveMatchesNow': 'এখন লাইভ ম্যাচ চলছে',
    'upcomingMatches': 'আজকের আগামী ম্যাচ',
    'noMatchesScheduled': 'আজ কোন ম্যাচ নেই।',
    'enterLobby': 'লবিতে প্রবেশ করুন',
    'txnIdRequired': 'লেনদেন আইডি (প্রয়োজনীয়)',
    'enterTxnId': 'আপনার পেমেন্ট থেকে লেনদেন আইডি লিখুন',
    'insufficientBalance': 'পর্যাপ্ত ব্যালেন্স নেই',
    'requiredAmount': 'প্রয়োজনীয় পরিমাণ',
    'topUpNow': 'এখনই রিচার্জ করুন',
    'myLinkedAccounts': 'আমার লিঙ্ক করা অ্যাকাউন্ট',
    'addNew': 'নতুন যোগ করুন',
    'selectLinkedAccount': 'আপনার জেতা টাকা পেতে একটি লিঙ্ক করা অ্যাকাউন্ট নির্বাচন করুন।',
    'withdrawAmount': 'উত্তোলনের পরিমাণ',
    'max': 'সর্বোচ্চ',
    'personal': 'ব্যগত',
    'community': 'কমিউনিটি',
    'noTransactions': 'এখনো কোন ব্যক্তিগত লেনদেন নেই।',
    'activity': 'কার্যক্রম',
    'confirmVia': 'এর মাধ্যমে নিশ্চিত করুন',
    'confirmWithdrawal': 'উত্তোলন নিশ্চিত করুন',
    'linkAccountTitle': 'অ্যাকাউন্ট লিঙ্ক করুন',
    'linkAccountSub': 'দ্রুত পেমেন্টের জন্য আপনার বিকাশ, নগদ বা বিনান্স লিঙ্ক করুন।',
    'selectProvider': 'প্রোভাইডার নির্বাচন করুন',
    'enterAccountNumber': 'অ্যাকাউন্ট নম্বর লিখুন',
    'linkAccountBtn': 'অ্যাকাউন্ট লিঙ্ক করুন',
    'cancel': 'বাতিল',
    'confirmDeletion': 'মুছে ফেলা নিশ্চিত করুন',
    'deleteConfirmationMsg': 'আপনি কি নিশ্চিত যে আপনি এই লিঙ্ক করা অ্যাকাউন্টটি সরাতে চান? এই কাজটি ফিরিয়ে নেওয়া যাবে না।',
    'deleteNow': 'এখনই মুছুন',
    'victory': 'বিজয়',
    'matchEnded': 'ম্যাচ শেষ হয়েছে',
    'finalPrize': 'চূড়ান্ত পুরস্কার',
    'winnings': 'জয়',
    'depositRequestSent': 'আমানতের অনুরোধ পাঠানো হয়েছে!',
    'depositSentSub': 'আমানতের অনুরোধ অ্যাডমিন অনুমোদনের জন্য পাঠানো হয়েছে।',
    'proceedToConfirm': 'নিশ্চিত করতে এগিয়ে যান',
    'addingFundsPrefix': 'আপনি আপনার সুরক্ষিত ওয়ালেটে',
    'addingFundsSuffix': 'যোগ করছেন।',
    'withdrawingFundsPrefix': 'আপনি আপনার',
    'withdrawingFundsSuffix': 'অ্যাকাউন্টে',
    'account': 'উত্তোলনের অনুরোধ করছেন',
    'notificationSettingsSub': 'আপনি কিভাবে সতর্কতা এবং আপডেট পাবেন তা নিয়ন্ত্রণ করুন।',
    'pushNotifications': 'পুশ নোটিফিকেশন',
    'pushNotificationsDesc': 'ম্যাচ এবং টুর্নামেন্টের জন্য সতর্কতা',
    'emailAlerts': 'ইমেল সতর্কতা',
    'emailAlertsDesc': 'আপনার অ্যাকাউন্ট এবং ওয়ালেট সম্পর্কে আপডেট',
    'tournamentUpdates': 'টুর্নামেন্ট আপডেট',
    'tournamentUpdatesDesc': 'নতুন বৈশিষ্ট্য এবং ইভেন্ট ঘোষণা',
    'selectLanguageSub': 'ইন্টারফেসের জন্য আপনার পছন্দের ভাষা নির্বাচন করুন।',
    'langEnglish': 'ইংরেজি',
    'regionUS': 'মার্কিন যুক্তরাষ্ট্র',
    'langBengali': 'বাংলা',
    'regionBD': 'বাংলাদেশ',
    'langHindi': 'হিন্দি',
    'regionIN': 'ভারত',
    'helpCenterSub': 'উত্তর খুঁজুন বা আমাদের সাপোর্ট টিমের সাথে যোগাযোগ করুন।',
    'needMoreHelp': 'আরও সাহায্য প্রয়োজন?',
    'supportTeamAvailability': 'আমাদের সাপোর্ট টিম যেকোনো সমস্যায় আপনাকে সাহায্য করার জন্য ২৪/৭ উপলব্ধ।',
    'chatWithUs': 'আমাদের সাথে চ্যাট করুন',
    'faqTitle': 'সচরাচর জিজ্ঞাস্য প্রশ্নাবলী',
    'faq1q': 'আমি কিভাবে একটি ম্যাচে যোগ দেব?',
    'faq1a': 'হোম স্ক্রিনে যান, একটি টুর্নামেন্ট নির্বাচন করুন এবং জয়েন ক্লিক করুন। আপনার পর্যাপ্ত ব্যালেন্স আছে কিনা নিশ্চিত করুন!',
    'faq2q': 'আমি কখন আমার জয়ী টাকা পাব?',
    'faq2a': 'ম্যাচ শেষ হওয়ার ১-২ ঘণ্টার মধ্যে জয়ী টাকা সাধারণত জমা হয়।',
    'faq3q': 'উত্তোলনের সীমা কি?',
    'faq3a': 'সর্বনিম্ন উত্তোলন ১০০ টাকা এবং সর্বোচ্চ ৫০,০০০ টাকা প্রতিদিন।',
    'faq4q': 'আমার তথ্য কি নিরাপদ?',
    'faq4a': 'হ্যাঁ, আমরা আপনার সমস্ত ব্যক্তিগত এবং আর্থিক তথ্য রক্ষা করতে এন্টারপ্রাইজ-গ্রেড এনক্রিপশন ব্যবহার করি।',
    'closeCenter': 'সেন্টার বন্ধ করুন',
    'waitASec': 'এক সেকেন্ড অপেক্ষা করুন!',
    'deleteMethodWarn': 'আপনি কি নিশ্চিত যে আপনি এই পেমেন্ট পদ্ধতিটি সরাতে চান? ভবিষ্যতে উত্তোলনের জন্য আপনাকে এটি আবার লিঙ্ক করতে হবে।',
    'yesRemoveIt': 'হ্যাঁ, এটি সরান',
    'keepMethod': 'পদ্ধতিটি রাখুন',
    'currencyPreference': 'কারেন্সি পছন্দ',
    'enterAmount': 'পরিমাণ লিখুন',
    'finalWinners': 'চূড়ান্ত বিজয়ী',
    'joinNowWithBet': 'এখনই যোগ দিন',
    'bettingTeam': 'বেটিং দল',
    'gameIdName': 'গেম আইডি নাম',
    'enterGameIdName': 'গেম আইডি নাম লিখুন',
    'joinedSuccessfully': 'সফলভাবে যোগদান করেছেন!',
    'dismiss': 'বাতিল করুন',
    'matchNotFound': 'ম্যাচ পাওয়া যায়নি',
    'arena': 'এরিনা',
    'ended': 'শেষ হয়েছে',
    'startIn': 'শুরু হবে',
    'noPaymentMethods': 'কোন পেমেন্ট পদ্ধতি উপলব্ধ নেই।',
    'rule': 'নিয়ম',
    'gameId': 'গেম আইডি',
    'support': 'সাপোর্ট',
    'matchRules': 'ম্যাচের নিয়মাবলী',
    'gameRoomId': 'গেম রুম আইডি',
    'roomId': 'রুম আইডি',
    'password': 'পাসওয়ার্ড',
    'matchDiscussion': 'ম্যাচ আলোচনা',
    'discussStrategies': 'লাইভ কৌশল এবং গেমপ্লে আলোচনা করুন',
    'typeMessage': 'আপনার বার্তা লিখুন...',
    'winPrize': 'জয়ের পুরস্কার',
    'perKill': 'প্রতি কিল',
    'map': 'ম্যাপ',
    'version': 'ভার্সন',
    'yourBalance': 'আপনার ব্যালেন্স',
    'continue': 'চালিয়ে যান',
    'joinedPill': 'যোগদান করেছেন',
    'fullPill': 'পূর্ণ',
    'joinNowPill': 'এখনই যোগ দিন',
    'gameRoomIdSub': 'রুম আইডি এবং পাসওয়ার্ড পেতে আপনাকে অবশ্যই এই ম্যাচে যোগ দিতে হবে।',
    'revealTimeMsgPrefix': 'রুম আইডি এবং পাসওয়ার্ড',
    'revealTimeMsgSuffix': 'মিনিট আগে প্রকাশ করা হবে।',
    'pending': 'অপেক্ষমান...',
    'updating': 'আপডেট হচ্ছে...',
    'match': 'ম্যাচ',
    'matches': 'ম্যাচ',
    'shortfall': 'ঘাটতি',
    'requiredFee': 'প্রয়োজনীয় ফি',
    'quickDepositNow': 'এখনই জমা করুন',
    'requestSent': 'অনুরোধ পাঠানো হয়েছে!',
    'quickDeposit': 'দ্রুত জমা',
    'amountToAdd': 'যোগ করার পরিমাণ',
    'submitDepositRequest': 'জমার অনুরোধ জমা দিন',
    'back': 'ফিরে যান',
    'insufficientBalanceSub': 'এই লেনদেনটি সম্পন্ন করার জন্য আপনার পর্যাপ্ত তহবিল নেই। আপনার ওয়ালেট টপ আপ করুন।',
    'depositSuccessSub': 'আপনার {amount} জমার অনুরোধ জমা দেওয়া হয়েছে। অ্যাডমিন অনুমোদন করলে ব্যালেন্স আপডেট হবে।',
    'awaitingCommunity': 'কমিউনিটির কার্যক্রমের অপেক্ষায়...',
    'player': 'একজন খেলোয়াড়',
    'deposited': 'জমা করেছেন',
    'withdrew': 'উত্তোলন করেছেন',
    'won': 'জিতেছেন',
    'in': 'এ',
    'performedAction': 'একটি কাজ করেছেন',
    'highRoller': 'বড় খেলোয়াড়',
    'you': 'আপনি',
    'obSkip': 'স্কিপ',
    'obNext': 'পরবর্তী',
    'obStart': 'শুরু করি',
    'obSlide1Title': 'বিড করার জন্য\nপ্রস্তুত তো?',
    'obSlide1Desc': 'আপনার লক্ষ্য স্থির করুন, বিড করুন এবং ফ্রি ফায়ার যুদ্ধক্ষেত্রে আধিপত্য বিস্তার করুন। আরও জানতে সোয়াইপ করুন।',
    'obSlide2Title': 'আপনার\nএফএফ স্কোয়াড বেছে নিন',
    'obSlide2Desc': 'আপনার প্রিয় ফ্রি ফায়ার দল বেছে নিন, আত্মবিশ্বাসের সাথে তাদের সমর্থন করুন এবং তাদের বারমুডা জয় করতে দেখুন।',
    'obSlide3Title': 'আপনার\nবিজয় দাবি করুন',
    'obSlide3Desc': 'যখন আপনার ফ্রি ফায়ার স্কোয়াড বুয়াহ নিবে তখন বড় পুরস্কার জিতুন! আপনার মহিমা অপেক্ষা করছে।',
    'welcomeBack': 'স্বাগতম',
    'joinTheElite': 'এলিট ক্লাবে যোগ দিন',
    'loginSub': 'অ্যাকশনে ফিরে যেতে আপনার ইমেল এবং পাসওয়ার্ড লিখুন।',
    'registerSub': 'জেএক্সএম ট্যুর ক্লাবের সাথে প্রতিযোগিতামূলক গেমিংয়ের রোমাঞ্চ অনুভব করুন।',
    'emailAddress': 'ইমেল ঠিকানা',
    'termsAgreement': 'আমি প্রত্যয়ন করছি যে আমার বয়স ১৮ বছর বা তার বেশি, এবং আমি পরিষেবার শর্তাবলীতে সম্মত।',
    'loginNowBtn': 'এখনই লগইন করুন',
    'registerAccountBtn': 'অ্যাকাউন্ট রেজিস্টার করুন',
    'processing': 'প্রসেসিং হচ্ছে...',
    'enterEmailPassword': 'ইমেল এবং পাসওয়ার্ড উভয়ই লিখুন।',
    'agreeTermsWarn': 'রেজিস্টার করতে আপনাকে অবশ্যই পরিষেবার শর্তাবলীতে সম্মত হতে হবে।',
    'enterNameWarn': 'আপনার নাম লিখুন।',
    'registrationSuccess': 'রেজিস্ট্রেশন সফল! লগইন করা হচ্ছে...',
    'emailInUse': 'এই ইমেলটি ইতিমধ্যে নিবন্ধিত।',
    'invalidCredentials': 'ভুল ইমেল বা পাসওয়ার্ড।',
    'weakPassword': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
    'authFailed': 'প্রমাণীকরণ ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'victoryCeremony': 'বিজয় অনুষ্ঠান',
    'matchComplete': 'ম্যাচ শেষ!',
    'ultimateChampion': 'চূড়ান্ত চ্যাম্পিয়ন',
    'eliteRunnerUp': 'এলিট রানার আপ',
    'bronzeContender': 'ব্রোঞ্জ প্রতিযোগী',
    'claimed': 'দাবি করা হয়েছে',
    'dismissCeremony': 'অনুষ্ঠান শেষ করুন',
    'supportBot': 'সাপোর্ট বট',
    'myWallet': 'আমার ওয়ালেট',
    'assignedSlot': 'নির্ধারিত স্লট',
    'slotNumber': 'স্লট নম্বর',
    'joinedEnd': 'অংশগ্রহণ শেষ',
    'timeExpired': 'সময় শেষ',
    'idle': 'অলস'
  },
  hi: {
    'home': 'होम',
    'wallet': 'वॉलेट',
    'myBets': 'इतिहास',
    'profile': 'प्रोफाइल',
    'live': 'लाइव',
    'join': 'शामिल हों',
    'joinNow': 'अभी शामिल हों',
    'totalPlayers': 'कुल खिलाड़ी',
    'prizePool': 'प्राइज़ पूल',
    'entryFee': 'एंट्री फीस',
    'matchDetails': 'मैच विवरण',
    'login': 'लॉगिन',
    'register': 'रजिस्टर',
    'balance': 'बैलेंस',
    'deposit': 'जमा करें',
    'withdraw': 'निकासी',
    'gamingArena': 'गेमिंग एरिना',
    'arenaSub': 'मैचों में शामिल हों और पुरस्कार जीतें',
    'active': 'सक्रिय',
    'completed': 'पूरा हुआ',
    'history': 'इतिहास',
    'details': 'विवरण',
    'confirmEntry': 'अपनी प्रविष्टि की पुष्टि करें',
    'success': 'सफल',
    'joined': 'शामिल हो गए!',
    'language': 'भाषा',
    'selectLanguage': 'भाषा चुनें',
    'players': 'खिलाड़ी',
    'entry': 'एंट्री',
    'slotsOccupied': 'स्লॉट भरे हुए हैं',
    'capacity': 'क्षमता',
    'fullHouse': 'हाउस फुल',
    'joinBattleground': 'मैदान में उतरें',
    'tacticalIntel': 'रणनीतिक जानकारी',
    'closesIn': 'समाप्ति समय:',
    'matchLive': 'मैच लाइव - खिलाड़ी शामिल हैं',
    'matchFull': 'मैच फुल - स्लॉट बंद',
    'soloInstruction': 'सोло मोड: कुल 48 सदस्य। प्रति प्रविष्टि केवल 1 सदस्य। 48 स्लॉट भरने पर कोई अन्य सदस्य शामिल नहीं हो सकता।',
    'duoInstruction': 'डुओ मोड: 24 टीमें (48 खिलाड़ी)। प्रति टीम 2 सदस्य। 24 टीमें शामिल होने पर कोई अन्य सदस्य शामिल नहीं हो सकता।',
    'squadInstruction': 'स्कवाद मोड: 12 टीमें (48 खिलाड़ी)। प्रति टीम 4 सदस्य। 12 टीमें शामिल होने पर कोई अन्य सदस्य शामिल नहीं हो सकता।',
    'settings': 'सेटिंग्स',
    'accountSecurity': 'अकाउंट सुरक्षा',
    'paymentMethods': 'भुगतान विधियां',
    'notifications': 'नोटिफिकेशन',
    'languageRegion': 'भाषा और क्षेत्र',
    'appearance': 'रंग-रूप',
    'helpCenter': 'सहायता केंद्र',
    'logout': 'लॉगआउट',
    'matchesWon': 'मैच जीते',
    'played': 'खेले गए',
    'matchFound': 'मैच मिला',
    'matchesFound': 'मैच मिले',
    'matchesLost': 'मैच हारे',
    'battleBuddy': 'बैटल बडी',
    'connections': 'कनेक्शन',
    'viewAll': 'सभी देखें',
    'editProfile': 'प्रोफ़ाइल संपादित करें',
    'fullName': 'पूরা नाम',
    'username': 'यूजर नेम',
    'updateProfile': 'प्रोफाइल अपडेट करें',
    'linkedAccounts': 'मेरे लिंक किए गए अकाउंट',
    'linkNew': 'नया अकाउंट लिंक करें',
    'selectGateway': 'गेटवे चुनें',
    'quickAmount': 'त्वरित राशि',
    'customAmount': 'कस्टम राशि',
    'addFunds': 'अभी फंड जोड़ें',
    'withdrawWinnings': 'जीत की निकासी',
    'requestWithdrawal': 'निकासी का अनुरोध करें',
    'recentActivity': 'हाल की गतिविधि',
    'noActivity': 'कोई हाल की गतिविधि नहीं',
    'transactionHistory': 'लेनदेन का इतिहास',
    'userId': 'यूज़र आईडी',
    'confirmSelection': 'चयन की पुष्टि करें',
    'savePreferences': 'पसंद सहेजें',
    'startTime': 'शुरू होगा',
    'myWallet': 'मेरा वॉलेट'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = (key: string, params?: Record<string, string>) => {
    let text = translations[language][key] || translations['en'][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
